name: Issues - Template
description: Template for filling out issues
body:
  - type: checkboxes
    attributes:
      label: Check List
      options:
      - label: I agree that I have read the [rules](https://github.com/Girabia/SYS-Compatibility/blob/main/Rules.md) about posting issues
        required: true
      - label: I accept the appropriate punishments if the [rules](https://github.com/Girabia/SYS-Compatibility/blob/main/Rules.md) are not followed
        required: true
  - type: textarea
    id: specifications
    attributes:
      label: Specifications
      placeholder: |
        Operational System: Windows 11
        CPU: Ryzen 5 5600 / I5-13400F
        GPU: GTX 3060
        RAM: 32GB
      value: |
        Operational System:
        CPU:
        GPU:
        RAM:
    validations:
      required: true
  - type: dropdown
    id: rating
    attributes: how is it running
      label: How is it running?
      options:
        - --Select One--
        - Perfect
        - Great
        - Ok
        - Bad
        - Intro/Menu
        - Won't Boot
    validations:
      required: true
  - type: dropdown
    id: rating
    attributes: engine
      label: What engine is used?
      options:
        - --Select One--
        - Vulkan
        - OpenGL
    validations:
      required: true
  - type: textarea
    id: additional-comments
    attributes:
      label: Additional comments
    validations:
      required: false
